services:
  real-time-chat-backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  real-time-chat-frontend:
    build: ./frontend
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'